---
- name: Deploy Docker Images
  hosts: localhost
  
  tasks:
    - name: Starting docker service
      service:
        name: docker
        state: started

    - name: Copy Docker Compose file from host machine
      copy:
        src: ./docker-compose.yml
        dest: ./

    - name: Running docker compose
      docker_compose:
        project_src: ./
        state: present
      become: true
      vars:
    	ansible_python_interpreter: /usr/bin/python3

