---
- name: Deploy Docker Images
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Starting docker service
      service:
        name: docker
        state: started

    - name: Copy Docker Compose file from host machine
      copy:
        src: ./docker-compose.yml
        dest: ./

    - name: run docker-compose file
      command: docker-compose up -d
      become: true

